export const CHANGE_INPUT_VALUE = 'change_inputValue'
export const ADD_TODO_ITEM = 'add_todo_item'
export const DELETE_TODO_ITEM = 'delete_item'
export const INIT_TODO_LIST = 'init_todo_list'
export const GET_INIT_LIST = 'get_init_list'